# Generated by Django 3.2.5 on 2021-07-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0002_auto_20210713_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foodhelper',
        ),
    ]
