# Generated by Django 3.2.5 on 2021-07-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0006_foodhelper_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmpassword',
        ),
    ]
