# Generated by Django 3.2.5 on 2021-07-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0007_remove_user_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhelper',
            name='profile_pic',
            field=models.FileField(default='media/default.png', upload_to='img'),
        ),
    ]
