# Generated by Django 3.2.5 on 2021-08-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0008_foodhelper_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhelper',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='foodhelper',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
