# Generated by Django 3.2.5 on 2021-08-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0018_addfood_food_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodhelper',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='AddFood',
        ),
        migrations.DeleteModel(
            name='foodhelper',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
