# Generated by Django 3.2.5 on 2021-08-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0020_addfood_foodhelper_user_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfood',
            old_name='picture_address',
            new_name='pickup_address',
        ),
    ]
