# Generated by Django 3.2.5 on 2021-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0023_addfood_foodhelper_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfood',
            name='food_picture',
            field=models.FileField(default='media/default.png', upload_to='img'),
        ),
    ]
