# Generated by Django 3.2.5 on 2021-08-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0024_alter_addfood_food_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfood',
            name='food_picture',
            field=models.FileField(default='media/default.jpg', upload_to='img'),
        ),
    ]
