# Generated by Django 3.2.5 on 2021-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0025_alter_addfood_food_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfood',
            old_name='pickup_address',
            new_name='picup_address',
        ),
        migrations.AlterField(
            model_name='addfood',
            name='food_picture',
            field=models.FileField(upload_to='media/img/'),
        ),
    ]
