# Generated by Django 3.2.5 on 2021-08-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0026_auto_20210804_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfood',
            old_name='picup_address',
            new_name='pickup_address',
        ),
    ]
