# Generated by Django 3.2.5 on 2021-08-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0032_addfood_feedback_foodhelper_ngo_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
