# Generated by Django 3.2.5 on 2021-08-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0034_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhelper',
            name='feedback',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
