# Generated by Django 3.2.5 on 2021-08-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0035_foodhelper_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodhelper',
            name='feedback',
        ),
    ]
