# Generated by Django 3.2.5 on 2021-09-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhelp', '0038_alter_feedback_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfood',
            name='food_video',
        ),
    ]
